### ISSUE TITLE
pyload-ng Restart Link/Restart Failed Error KeyError: 'id'

### ISSUE THREAD

**Issue by ProfessorPinguino** [pyload/pyload#4276]
### Description

When clicking "Restart Link" or "Restart Failed" I get a Error notification (logs below). I'm using the latest Linuxserver docker container V0.5.0

### Debug log

```


4662 | 2023-03-31 09:14:55 | DEBUG | pyload.webui | 'id'
-- | -- | -- | -- | --
4663 | ? | ? | ? | Traceback (most recent call last):
4664 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
4665 | ? | ? | ? | rv = self.dispatch_request()
4666 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
4667 | ? | ? | ? | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
4668 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 36, in rpc
4669 | ? | ? | ? | s = set_session(user_info)
4670 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/pyload/webui/app/helpers.py", line 133, in set_session
4671 | ? | ? | ? | "id": user_info["id"],
4672 | ? | ? | ? | KeyError: 'id'


```

**Comment by GammaC0de** [comment]
I believe this is now fixed, please confirm.

**Comment by egabosh** [comment]
not fixed for me
```
[2023-06-30 16:03:50]  DEBUG         pyload.webui  'id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 36, in rpc
    s = set_session(user_info)
  File "/usr/local/lib/python3.10/site-packages/pyload/webui/app/helpers.py", line 147, in set_session
    "id": user_info["id"],
KeyError: 'id'
```
Using docker with traefik
```
version: '3.6'
services:
  pyload.:
    #build: https://github.com/pyload/pyload.git
    build:
      context: pyload
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /data-crypt/pyload:/downloads
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      # HTTPS
      - traefik.http.routers.pyload-pyload.rule=Host(`pyload.`)
      - traefik.http.routers.pyload-pyload.entrypoints=https
      - traefik.http.routers.pyload-pyload.tls=true
      # Proxy to service-port
      - traefik.http.services.pyload-pyload.loadbalancer.server.port=8000
      - traefik.http.routers.pyload-pyload.service=pyload-defiant
      # cert via letsencrypt
      - traefik.http.routers.pyload-pyload.tls.certresolver=letsencrypt
      # Traefik network
      - traefik.docker.network=traefik
      # activate secHeaders@file
      # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
      - traefik.http.middlewares.pyload-auth.basicauth.users=pyload:$$apr1$$MGLvkRPT$$F4RALxFiNOeONanPwIYji0
      - traefik.http.routers.pyload-pyload.middlewares=secHeaders@file,pyload-auth
    ports:
      # for remote clients like android app
      - 7227:7227
      # click and load
      - 9666:9666
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1version: '3.6'
services:
  pyload.:
    #build: https://github.com/pyload/pyload.git
    build:
      context: pyload
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /data-crypt/pyload:/downloads
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      # HTTPS
      - traefik.http.routers.pyload-pyload.rule=Host(`pyload.`)
      - traefik.http.routers.pyload-pyload.entrypoints=https
      - traefik.http.routers.pyload-pyload.tls=true
      # Proxy to service-port
      - traefik.http.services.pyload-pyload.loadbalancer.server.port=8000
      - traefik.http.routers.pyload-pyload.service=pyload-defiant
      # cert via letsencrypt
      - traefik.http.routers.pyload-pyload.tls.certresolver=letsencrypt
      # Traefik network
      - traefik.docker.network=traefik
      # activate secHeaders@file
      - traefik.http.routers.pyload-pyload.middlewares=secHeaders@file
    ports:
      # for remote clients like android app
      - 7227:7227
      # click and load
      - 9666:9666


networks:
  traefik:
    external: true

networks:
  traefik:
    external: true
```
